// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coinbase/chainsformer/internal/utils/xarrow (interfaces: TableWriter)
//
// Generated by this command:
//
//	mockgen -destination internal/utils/xarrow/mocks/mocks.go -package xarrowmocks github.com/coinbase/chainsformer/internal/utils/xarrow TableWriter
//

// Package xarrowmocks is a generated GoMock package.
package xarrowmocks

import (
	reflect "reflect"

	array "github.com/apache/arrow/go/v10/arrow/array"
	gomock "go.uber.org/mock/gomock"
)

// MockTableWriter is a mock of TableWriter interface.
type MockTableWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTableWriterMockRecorder
}

// MockTableWriterMockRecorder is the mock recorder for MockTableWriter.
type MockTableWriterMockRecorder struct {
	mock *MockTableWriter
}

// NewMockTableWriter creates a new mock instance.
func NewMockTableWriter(ctrl *gomock.Controller) *MockTableWriter {
	mock := &MockTableWriter{ctrl: ctrl}
	mock.recorder = &MockTableWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableWriter) EXPECT() *MockTableWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTableWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTableWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTableWriter)(nil).Close))
}

// Flush mocks base method.
func (m *MockTableWriter) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockTableWriterMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockTableWriter)(nil).Flush))
}

// RecordBuilder mocks base method.
func (m *MockTableWriter) RecordBuilder() *array.RecordBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBuilder")
	ret0, _ := ret[0].(*array.RecordBuilder)
	return ret0
}

// RecordBuilder indicates an expected call of RecordBuilder.
func (mr *MockTableWriterMockRecorder) RecordBuilder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBuilder", reflect.TypeOf((*MockTableWriter)(nil).RecordBuilder))
}
